// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function HomePath(arg1) {
  return window['go']['main']['App']['HomePath'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListDirAs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListDirAs'](arg1, arg2, arg3, arg4);
}

export function ListDistros() {
  return window['go']['main']['App']['ListDistros']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileAs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadFileAs'](arg1, arg2, arg3, arg4);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadFileBase64As(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadFileBase64As'](arg1, arg2, arg3, arg4);
}

export function RunWSLCommand(arg1) {
  return window['go']['main']['App']['RunWSLCommand'](arg1);
}

export function RunWSLCommandAs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunWSLCommandAs'](arg1, arg2, arg3, arg4);
}

export function SetBackground(arg1, arg2) {
  return window['go']['main']['App']['SetBackground'](arg1, arg2);
}

export function SetDefaultLinuxDistro(arg1) {
  return window['go']['main']['App']['SetDefaultLinuxDistro'](arg1);
}

export function SetDefaultLinuxUser(arg1) {
  return window['go']['main']['App']['SetDefaultLinuxUser'](arg1);
}

export function TogglePinnedFolder(arg1) {
  return window['go']['main']['App']['TogglePinnedFolder'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteFileAs(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['WriteFileAs'](arg1, arg2, arg3, arg4, arg5);
}
