// @ts-check
// Wails bindings for the App struct. ihu frontend talks exclusively to the
// Go backend via window.go.main.App — the bindings are generated by Wails and
// extended here for the ihu-specific methods.

const go = window.go.main.App

export function Greet(arg1) {
  return go.Greet(arg1)
}

export function GetBootData() {
  return go.GetBootData()
}

export function GetConfig() {
  return go.GetConfig()
}

export function SetWelcomeDisabled(arg1) {
  return go.SetWelcomeDisabled(arg1)
}

export function SetDefaultLinuxPath(arg1) {
  return go.SetDefaultLinuxPath(arg1)
}

export function SetDefaultLinuxUser(arg1) {
  return go.SetDefaultLinuxUser(arg1)
}

export function SetDefaultLinuxDistro(arg1) {
  return go.SetDefaultLinuxDistro(arg1)
}

export function TogglePinnedFolder(arg1) {
  return go.TogglePinnedFolder(arg1)
}

export function SetBackground(arg1, arg2) {
  return go.SetBackground(arg1, arg2)
}

export function ListDir(arg1) {
  return go.ListDir(arg1)
}

export function HomePath(arg1) {
  return go.HomePath(arg1)
}

export function ListDistros() {
  return go.ListDistros()
}

export function ListUsers() {
  return go.ListUsers()
}

export function ReadFile(arg1) {
  return go.ReadFile(arg1)
}

export function RunWSLCommand(arg1) {
  return go.RunWSLCommand(arg1)
}

export function ReadFileBase64(arg1) {
  return go.ReadFileBase64(arg1)
}
