// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {wsl} from '../models';

export function GetConfig():Promise<config.WSLConfig>;

export function GetStats():Promise<wsl.SystemStats>;

export function HomePath(arg1:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<wsl.Entry>>;

export function ListDirAs(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<wsl.Entry>>;

export function ListDistros():Promise<Array<string>>;

export function ListUsers():Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileAs(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadFileBase64As(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function RunWSLCommand(arg1:string):Promise<string>;

export function RunWSLCommandAs(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function SetBackground(arg1:string,arg2:string):Promise<config.WSLConfig>;

export function SetDefaultLinuxDistro(arg1:string):Promise<config.WSLConfig>;

export function SetDefaultLinuxUser(arg1:string):Promise<config.WSLConfig>;

export function TogglePinnedFolder(arg1:string):Promise<config.WSLConfig>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteFileAs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;
